### ISSUE TITLE
audio distortion

### ISSUE THREAD

**Issue by Catherinehui** [Wang-Jingrun/DCCRN#1]
您好，我跑通了您的代码，但是我最后导出来听音频失真了，包括原始的和噪音的，这跟我跑的epoch有关吗，我没有设置很大

**Comment by Wang-Jingrun** [comment]
如果计算的评价指标没有问题，我猜测你可能是保存的时候方式不对。通过网络后的音频需要进行一次归一化后，再转换成int16格式后保存：

```
wav = wav / ((numpy.sqrt(numpy.sum(wav ** 2)) / ((wav.shape[0]) + 1e-7)) + 1e-7)
soundfile.write(f'samples.wav', wav.astype('int16'), 16000)
```

因为音频文件都是通过整型存储的，但是在数据处理的时候后会转成float型（soundfile等库读取后的音频数据会自动转换成float型，并且大小限制在 (-1, 1) 之间），因此保存的时候不能直接保存。

如果想了解更多，可以看一下这篇博客：https://blog.csdn.net/qq_37851620/article/details/127149729
