### ISSUE TITLE
audio question

### ISSUE THREAD

**Issue by Catherinehui** [Wang-Jingrun/DCCRN#2]
[您好,我按照您的建议，发现自己是由于没有将Voicebank测试集进行下采样到16000，后面经过下采样后结果好了一些，但是所有音频还是失真，我并没有改动您的代码，我现在将自己的测试结果音频上传，如果您有时间可否帮我听一下是否和您测试的一样，因为我发现我测试的指标和您是差不多的，最近这个代码很急，所以请求您的帮助，这是我的微信联系方式：17861316313，不知是否可以跟您联系并向您请教一下，万分感谢！
[Voicebank_results.zip](https://github.com/Wang-Jingrun/DCCRN/files/11188840/Voicebank_results.zip)

**Comment by Wang-Jingrun** [comment]
已经加你了，建议可以把回复删除了，以免泄露个人信息
